# Generated by Django 4.1.2 on 2023-04-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0005_alter_book_category'),
        ('authentication', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='stamp',
        ),
        migrations.AddField(
            model_name='customuser',
            name='Borrow',
            field=models.ManyToManyField(to='webpage.book'),
        ),
    ]
