# Generated by Django 4.1.2 on 2023-03-28 09:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("book_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.MinLengthValidator(6)],
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("type", models.CharField(max_length=20)),
                ("genre", models.CharField(max_length=20)),
                ("quantity", models.IntegerField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="webpage.author"
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webpage.publisher",
                    ),
                ),
            ],
        ),
    ]
