# Generated by Django 4.1.2 on 2023-04-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webpage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.CharField(
                choices=[
                    ("Horror", "Horror"),
                    ("Thriller", "Thriller"),
                    ("Romance", "Romance"),
                    ("Sci-fi", "Sci-fi"),
                    ("Fantasy", "Fantasy"),
                    ("Mystery", "Mystery"),
                    ("Food", "Food"),
                    ("Comedy", "Comedy"),
                    ("Action", "Action"),
                    ("self-improvement", "self-improvement"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="type",
            field=models.CharField(
                choices=[
                    ("01", "นิยาย"),
                    ("02", "นิทาน"),
                    ("03", "วิชาการ"),
                    ("04", "นิตยาสาร"),
                    ("05", "โดจินชิ"),
                    ("06", "การ์ตูน"),
                    ("07", "ศาสนา"),
                ],
                max_length=20,
            ),
        ),
    ]
