# Generated by Django 4.1.4 on 2023-04-06 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webpage", "0003_book_image_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="type",
            new_name="category",
        ),
    ]
