# Generated by Django 4.1.2 on 2023-04-11 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webpage", "0005_alter_book_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="image_link",
        ),
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
